//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.CarInfo = new HashSet<CarInfo>();
        }
    
        public int Car_Id { get; set; }
        public string Car_MarkName { get; set; }
        public string Car_Description { get; set; }
    
        public virtual ICollection<CarInfo> CarInfo { get; set; }
    }
}
