//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceDBEntities2 : DbContext
    {
        public ServiceDBEntities2()
            : base("name=ServiceDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Car { get; set; }
        public DbSet<CarInfo> CarInfo { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Personal> Personal { get; set; }
        public DbSet<Profession> Profession { get; set; }
        public DbSet<Regestration> Regestration { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<ServicesInfo> ServicesInfo { get; set; }
        public DbSet<Spare> Spare { get; set; }
        public DbSet<Stock> Stock { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
