//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public Personal()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int Personal_Id { get; set; }
        public string Personal_Login { get; set; }
        public string Personal_Password { get; set; }
        public int Proffesion_Id_FK { get; set; }
        public string Personal_Name { get; set; }
        public string Personal_Surname { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Profession Profession { get; set; }
    }
}
