//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public Profession()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public int Profession_Id { get; set; }
        public string Profession_Name { get; set; }
    
        public virtual ICollection<Personal> Personal { get; set; }
    }
}
