//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spare
    {
        public int Spare_Id { get; set; }
        public string Spare_Name { get; set; }
        public string Spare_Description { get; set; }
        public int Store_Id_FK { get; set; }
        public int Stock_Id_FK { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Store Store { get; set; }
    }
}
