//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.Spare = new HashSet<Spare>();
        }
    
        public int Stock_Id { get; set; }
        public int Clients_Id_FK { get; set; }
        public string Stock_ProductName { get; set; }
        public string Stock_Count { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Spare> Spare { get; set; }
    }
}
